### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by nikhiljha** [edufolly/flutter_mobile_vision#13]
Possibly related to #7 - except it happens when permission is granted. It crashes the first time (when the permission dialog is there), and then it works just fine.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4360)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:4402)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1808)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterNativeView$1.reply (FlutterNativeView.java:174)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:199)
  at io.github.edufolly.fluttermobilevision.FlutterMobileVisionPlugin.onActivityResult (FlutterMobileVisionPlugin.java:188)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:210)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:139)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:138)
  at android.app.Activity.dispatchActivityResult (Activity.java:7454)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4353)
```

```
  Future scan() async {
    List<Barcode> barcodes = [];
    try {
      barcodes = await FlutterMobileVision.scan(
        fps: 15.0,
      );
      SharedPreferences prefs = await SharedPreferences.getInstance();
      prefs.setString("usr_idNumber", barcodes[0].rawValue);
      setState(() {
        id_number = barcodes[0].rawValue;
      });
    } on Exception {
      setState(() {
              errorText = "An error occured.";
            });
      barcodes.add(new Barcode('Failed to get barcode.'));
    }
  }
```

**Comment by nikhiljha** [comment]
This might be more helpful:

```
D/AndroidRuntime( 7062): Shutting down VM
E/AndroidRuntime( 7062): FATAL EXCEPTION: main
E/AndroidRuntime( 7062): Process: app.teamepic.portolapp, PID: 7062
E/AndroidRuntime( 7062): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9010, result=13, data=null} to activity {app.teamepic.portolapp/io.flutter.demo.gallery.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7062):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4349)
E/AndroidRuntime( 7062):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4391)
E/AndroidRuntime( 7062):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 7062):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 7062):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 7062):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
E/AndroidRuntime( 7062):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7062):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 7062):        at android.app.ActivityThread.main(ActivityThread.java:6642)
E/AndroidRuntime( 7062):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7062):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 7062):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 7062): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7062):        at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime( 7062):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/AndroidRuntime( 7062):        at io.github.edufolly.fluttermobilevision.FlutterMobileVisionPlugin.onActivityResult(FlutterMobileVisionPlugin.java:188)
E/AndroidRuntime( 7062):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 7062):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 7062):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 7062):        at android.app.Activity.dispatchActivityResult(Activity.java:7449)
E/AndroidRuntime( 7062):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4342)
E/AndroidRuntime( 7062):        ... 11 more
I/Process ( 7062): Sending signal. PID: 7062 SIG: 9
```

**Comment by edufolly** [comment]
Hi @nikhiljha,

released a new version, please test. Waiting for your feedback.

**Comment by edufolly** [comment]
I've just published a new demo app. Check it out... [Flutter Mobile Vision Start](https://github.com/edufolly/flutter_mobile_vision_start)

Please feel free to ask for further help here.
